name: build

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  DOTNET_VERSION: 6.0.x
  CONFIGURATION: Release

jobs:
  build:    
    runs-on: ubuntu-latest   
    name: Build and test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
        
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }}

    - name: Test
      run: dotnet test --configuration ${{ env.CONFIGURATION }}